/**
 * gen-fixtures.ts — converts circuits/fixtures/proof.json + public.json
 * into contracts/por-verifier/src/test_fixtures.rs
 *
 * Encoding rules (Ethereum-compatible / soroban-sdk 26.1.0):
 *   Bn254G1Affine = BytesN<64>  = BE32(X) || BE32(Y)
 *   Bn254G2Affine = BytesN<128> = BE32(x_c1)||BE32(x_c0) || BE32(y_c1)||BE32(y_c0)
 *     (snarkjs pi_b = [[x_c0, x_c1], [y_c0, y_c1], …])
 *
 * Run: bun run contracts/por-verifier/gen/gen-fixtures.ts
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "../../..");

const proof = JSON.parse(
  readFileSync(join(ROOT, "circuits/fixtures/proof.json"), "utf8")
);
const pub_ = JSON.parse(
  readFileSync(join(ROOT, "circuits/fixtures/public.json"), "utf8")
);

// ── helpers ──────────────────────────────────────────────────────────────────

function toBE32(decimal: string): Uint8Array {
  let n = BigInt(decimal);
  const out = new Uint8Array(32);
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(n & 0xffn);
    n >>= 8n;
  }
  if (n !== 0n) throw new Error(`Value ${decimal} does not fit in 32 bytes`);
  return out;
}

function rustByteArray(bytes: Uint8Array): string {
  return (
    "[\n        " +
    [...bytes].map((b) => `0x${b.toString(16).padStart(2, "0")}`).join(", ") +
    ",\n    ]"
  );
}

function concat(...arrays: Uint8Array[]): Uint8Array {
  const total = arrays.reduce((a, b) => a + b.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const a of arrays) {
    out.set(a, offset);
    offset += a.length;
  }
  return out;
}

// ── G1 (pi_a, pi_c) ──────────────────────────────────────────────────────────
// pi_a = [x, y, "1"]
const pi_a_bytes = concat(toBE32(proof.pi_a[0]), toBE32(proof.pi_a[1]));
const pi_c_bytes = concat(toBE32(proof.pi_c[0]), toBE32(proof.pi_c[1]));

// ── G2 (pi_b) ─────────────────────────────────────────────────────────────────
// snarkjs: pi_b = [[x_c0, x_c1], [y_c0, y_c1], _]
// Soroban encoding: BE32(x_c1) || BE32(x_c0) || BE32(y_c1) || BE32(y_c0)
const [x_c0, x_c1] = proof.pi_b[0];
const [y_c0, y_c1] = proof.pi_b[1];
const pi_b_bytes = concat(toBE32(x_c1), toBE32(x_c0), toBE32(y_c1), toBE32(y_c0));

// ── Public signals ─────────────────────────────────────────────────────────────
// public.json = [root, total, epoch]
const [root_dec, total_dec, epoch_dec] = pub_ as string[];

// Produce big-endian 32-byte representations for U256 construction in Rust
const root_be  = toBE32(root_dec);
const total_be = toBE32(total_dec);
const epoch_be = toBE32(epoch_dec);

// ── emit Rust ────────────────────────────────────────────────────────────────

const rs = `\
// AUTO-GENERATED by contracts/por-verifier/gen/gen-fixtures.ts — DO NOT EDIT.
// Source: circuits/fixtures/proof.json + public.json
// Signals: [root=${root_dec}, total=${total_dec}, epoch=${epoch_dec}]
//
// Encoding:
//   Bn254G1Affine = BytesN<64>  = BE32(X) || BE32(Y)
//   Bn254G2Affine = BytesN<128> = BE32(x_c1)||BE32(x_c0) || BE32(y_c1)||BE32(y_c0)

use soroban_sdk::{Env, BytesN, U256, Bytes};
use soroban_sdk::crypto::bn254::{
    Bn254G1Affine, Bn254G2Affine,
    BN254_G1_SERIALIZED_SIZE, BN254_G2_SERIALIZED_SIZE,
};
use crate::groth16_verifier::Proof;

// pi_a — G1 point: BE32(X) || BE32(Y)
const PI_A: [u8; BN254_G1_SERIALIZED_SIZE] = ${rustByteArray(pi_a_bytes)};

// pi_b — G2 point: BE32(x_c1)||BE32(x_c0) || BE32(y_c1)||BE32(y_c0)
const PI_B: [u8; BN254_G2_SERIALIZED_SIZE] = ${rustByteArray(pi_b_bytes)};

// pi_c — G1 point: BE32(X) || BE32(Y)
const PI_C: [u8; BN254_G1_SERIALIZED_SIZE] = ${rustByteArray(pi_c_bytes)};

// Public signals (big-endian 32-byte representation of each decimal value)
const ROOT_BE:  [u8; 32] = ${rustByteArray(root_be)};
const TOTAL_BE: [u8; 32] = ${rustByteArray(total_be)};
const EPOCH_BE: [u8; 32] = ${rustByteArray(epoch_be)};

/// Returns (proof, root: U256, total: u64, epoch: u64) for use in tests.
pub fn valid_attestation(env: &Env) -> (Proof, U256, u64, u64) {
    let a = Bn254G1Affine::from_bytes(BytesN::from_array(env, &PI_A));
    let b = Bn254G2Affine::from_bytes(BytesN::from_array(env, &PI_B));
    let c = Bn254G1Affine::from_bytes(BytesN::from_array(env, &PI_C));
    let proof = Proof { a, b, c };

    let root  = U256::from_be_bytes(env, &Bytes::from_array(env, &ROOT_BE));
    let total: u64 = ${total_dec}u64;
    let epoch: u64 = ${epoch_dec}u64;

    (proof, root, total, epoch)
}
`;

const outPath = join(ROOT, "contracts/por-verifier/src/test_fixtures.rs");
writeFileSync(outPath, rs);
console.log(`Written: ${outPath}`);
console.log(`pi_a: ${[...pi_a_bytes].map(b => b.toString(16).padStart(2,'0')).join('')}`);
console.log(`pi_b: ${[...pi_b_bytes].map(b => b.toString(16).padStart(2,'0')).join('')}`);
console.log(`pi_c: ${[...pi_c_bytes].map(b => b.toString(16).padStart(2,'0')).join('')}`);
