// PLACEHOLDER — interface stub only. The flight-fixture generator (a parallel
// task) OVERWRITES this file with real proof/VK bytes; its header will read
// "AUTO-GENERATED". Do not edit this file: it exists solely so the flight tests
// compile against a fixed interface until the generated bytes land. All bodies
// panic via `unimplemented!()`, which is why every test that calls one of these
// functions is `#[ignore = "awaiting flight fixture"]`.

use crate::groth16::{Proof, VerificationKey};
use soroban_sdk::{Env, U256};

pub struct FlightFixture {
    pub proof: Proof,
    pub shipment_id: u64,
    pub c_s: U256,
    pub carrier_pk_commit: U256,
    pub head: U256,
    pub corridor_root: U256,
    pub t_0: u64,
    pub t_n: u64,
}

pub struct DroneDelivery {
    pub proof: Proof,
    pub nullifier: U256,
    pub ts: u64,
}

pub fn flight_vk(_env: &Env) -> VerificationKey {
    unimplemented!()
}

pub fn valid_flight(_env: &Env) -> FlightFixture {
    unimplemented!()
}

pub fn drone_delivery(_env: &Env) -> DroneDelivery {
    unimplemented!()
}
